### ISSUE TITLE
Tweet embedding doesn't work on iOS

### ISSUE THREAD

**Issue by figengungor** [aker99/social_embed_webview#4]
Thanks for the library. It works on Android but I see a white container instead of tweets on iOS.

**Comment by aker99** [comment]
@figengungor please check now. As flutter official team has released a stable version for *webview_flutter*, possibly that could have already fixed this issue. 
PS: Lacking resource to test on iOS, your feedback would help.

**Comment by adaskaliuk** [comment]
Still not working :( 
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-12-17 at 12 02 28](https://user-images.githubusercontent.com/28977270/102473107-bd7ba580-405f-11eb-9b43-720feb4c4242.png)

**Comment by JonasDev17** [comment]
Yeah, it doesn't render. No error thrown...

**Comment by tudorcodarnai** [comment]
Guys I figured it out: it's because of the implementation of the navigationDelegate in lib/social_media_webview.dart

This problem affects all social plugins: Facebook, Twitter, YouTube and Instagram.

```dart
... 
navigationDelegate: (navigation) async {
          final url = navigation.url;
          if (await canLaunch(url)) {
            launch(url);
          }
          return NavigationDecision.prevent;
        });
```

the code must be changed to something like this: 

```dart
...
navigationDelegate: (navigation) async {
          if(navigation.isForMainFrame && await canLaunch(navigation.url)) {
            launch(navigation.url);
            return NavigationDecision.prevent;
          }
          return NavigationDecision.navigate;
        });
```

Indeed on Android it was working fine, but apparently iOS doesn't like ```NavigationDecision.prevent``` for all navigations. Hence the blank displays. 

This should fix the blanks on all social plugins on iOS.

@aker99 let me know if you want me to make a branch and push the change.

**Comment by aker99** [comment]
@tudorcodarnai sure, please go forward with it.
